<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED>

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,Step*,DIter*,Action*,Summary?,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,NodeArgs) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Hora estándar Sudamérica E.">
<General productName="QuickTest Professional" productVer="9.0" os="Windows 2000" host="GERSIS00127223"><DocLocation><![CDATA[[QualityCenter] Subject\3.0 AUTOMATIZACION DE CASOS DE TESTEO BANCA INTERNET\CT152 - Activar operacion (BI C014)\CT152 - Activar Operacion]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[CT152 - Activar Operacion]]></DName>
<Res><![CDATA[Run_1-19_10-22-8]]></Res>
<TSet><![CDATA[Root\Banca Internet\Ciclo Automatico]]></TSet>
<TInst><![CDATA[1]]></TInst>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="6" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Activar la Operacion]]></AName>
<Step rID="T5" >
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:42:17]]></Time>
<Step rID="T6" >
<Obj plainTxt="False" ><![CDATA[Alerta de seguridad]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[19/1/07 - 9:42:17]]></Time>
<Step rID="T7" >
<Obj plainTxt="False" ><![CDATA[Sí.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:42:17]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="13" >
<Disp><![CDATA[Sí.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" >
<Disp><![CDATA[Alerta de seguridad]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8" >
<Obj plainTxt="False" ><![CDATA[Autenticación del cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[19/1/07 - 9:42:18]]></Time>
<Step rID="T9" >
<Obj plainTxt="False" ><![CDATA[El sitio Web que quiere.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["203300 - REY Y MILBERG SA"]]></Details>
<Time><![CDATA[19/1/07 - 9:42:18]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="16" >
<Disp><![CDATA[El sitio Web que quiere.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[2099036]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10" >
<Obj plainTxt="False" ><![CDATA[Aceptar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:42:19]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="18" >
<Disp><![CDATA[Aceptar.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" >
<Disp><![CDATA[Autenticación del cliente]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[1968088]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-3-0-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:42:22]]></Time>
<Step rID="T12" >
<Obj plainTxt="False" ><![CDATA[docType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["DNI PARA EXTRANJEROS"]]></Details>
<Time><![CDATA[19/1/07 - 9:42:23]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="22" >
<Disp><![CDATA[docType.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro").WebList("docType")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13" >
<Obj plainTxt="False" ><![CDATA[nroDoc.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["93975837"]]></Details>
<Time><![CDATA[19/1/07 - 9:42:24]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="24" >
<Disp><![CDATA[nroDoc.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro").WebEdit("nroDoc")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="21" >
<Disp><![CDATA[Banca Internet - v3-3-0-prepro]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-4-0-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:42:35]]></Time>
<Step rID="T15" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-4-0-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:42:35]]></Time>
<Step rID="T16" >
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["testing6"]]></Details>
<Time><![CDATA[19/1/07 - 9:42:35]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="29" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-4-0-prepro").WebEdit("password")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17" >
<Obj plainTxt="False" ><![CDATA[LogIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "LogIn" started.]]></Details>
<Time><![CDATA[19/1/07 - 9:42:37]]></Time>
<NodeArgs eType="Transaction" icon="12" nRep="30" nType="Start Transaction" >
<Disp><![CDATA[LogIn]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18" >
<Obj plainTxt="False" ><![CDATA[Ingresar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:42:37]]></Time>
<NodeArgs eType="Replay" icon="13" nRep="32" >
<Disp><![CDATA[Ingresar.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-4-0-prepro").WebButton("Ingresar")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="28" >
<Disp><![CDATA[Banca Internet - v3-4-0-prepro]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-4-0-prepro")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19" >
<Obj plainTxt="False" ><![CDATA[IE 6.0 - Banca Internet]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:11]]></Time>
<Step rID="T20" >
<Obj plainTxt="False" ><![CDATA[Operaciones Preparadas.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 10000]]></Details>
<Time><![CDATA[19/1/07 - 9:44:11]]></Time>
<NodeArgs eType="Replay" icon="14" nRep="36" >
<Disp><![CDATA[Operaciones Preparadas.WaitProperty]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("IE 6.0 - Banca Internet").WebElement("Operaciones Preparadas")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21" >
<Obj plainTxt="False" ><![CDATA[LogIn]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "LogIn" ended with "Pass" status (Total Duration: 94.3411 sec Wasted Time: 0.0123 sec).]]></Details>
<Time><![CDATA[19/1/07 - 9:44:11]]></Time>
<NodeArgs eType="Transaction" icon="15" nRep="37" nType="End Transaction" >
<Disp><![CDATA[LogIn]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22" >
<Obj plainTxt="False" ><![CDATA[Operaciones Preparadas.Fire Web Event]]></Obj>
<Details plainTxt="False" ><![CDATA["onmouseover"]]></Details>
<Time><![CDATA[19/1/07 - 9:44:13]]></Time>
<NodeArgs eType="Replay" icon="14" nRep="39" >
<Disp><![CDATA[Operaciones Preparadas.Fire Web Event]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("IE 6.0 - Banca Internet").WebElement("Operaciones Preparadas")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23" >
<Obj plainTxt="False" ><![CDATA[Operaciones Preparadas.Fire Web Event]]></Obj>
<Details plainTxt="False" ><![CDATA["rollover"]]></Details>
<Time><![CDATA[19/1/07 - 9:44:13]]></Time>
<NodeArgs eType="Replay" icon="14" nRep="41" >
<Disp><![CDATA[Operaciones Preparadas.Fire Web Event]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("IE 6.0 - Banca Internet").WebElement("Operaciones Preparadas")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24" >
<Obj plainTxt="False" ><![CDATA[Seleccionar_Firmar_Operaciones_Pendientes]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Seleccionar_Firmar_Operaciones_Pendientes" started.]]></Details>
<Time><![CDATA[19/1/07 - 9:44:13]]></Time>
<NodeArgs eType="Transaction" icon="12" nRep="42" nType="Start Transaction" >
<Disp><![CDATA[Seleccionar_Firmar_Operaciones_Pendientes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="35" >
<Disp><![CDATA[IE 6.0 - Banca Internet]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("IE 6.0 - Banca Internet")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="27" >
<Disp><![CDATA[Banca Internet - v3-4-0-prepro]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25" >
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:44:14]]></Time>
<Step rID="T26" >
<Obj plainTxt="False" ><![CDATA[IE 6.0 - Banca Internet]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:14]]></Time>
<Step rID="T27" >
<Obj plainTxt="False" ><![CDATA[Firmar operaciones pendientes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:14]]></Time>
<NodeArgs eType="Replay" icon="14" nRep="47" >
<Disp><![CDATA[Firmar operaciones pendientes.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("IE 6.0 - Banca Internet").WebElement("Firmar operaciones pendientes")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="46" >
<Disp><![CDATA[IE 6.0 - Banca Internet]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("IE 6.0 - Banca Internet")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="45" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-4-0-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:44:24]]></Time>
<Step rID="T29" >
<Obj plainTxt="False" ><![CDATA[IE 6.0 - Banca Internet_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:24]]></Time>
<Step rID="T30" >
<Obj plainTxt="False" ><![CDATA[flecha_subtitulo.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["innertext", "Operaciones pendientes de firma ", "Operaciones pendientes de firma ", 10000]]></Details>
<Time><![CDATA[19/1/07 - 9:44:25]]></Time>
<NodeArgs eType="Replay" icon="14" nRep="52" >
<Disp><![CDATA[flecha_subtitulo.WaitProperty]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("IE 6.0 - Banca Internet 2").WebElement("flecha subtitulo")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T31" >
<Obj plainTxt="False" ><![CDATA[Seleccionar_Firmar_Operaciones_Pendientes]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Seleccionar_Firmar_Operaciones_Pendientes" ended with "Pass" status (Total Duration: 12.1226 sec Wasted Time: 0.2052 sec).]]></Details>
<Time><![CDATA[19/1/07 - 9:44:25]]></Time>
<NodeArgs eType="Transaction" icon="15" nRep="53" nType="End Transaction" >
<Disp><![CDATA[Seleccionar_Firmar_Operaciones_Pendientes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="51" >
<Disp><![CDATA[IE 6.0 - Banca Internet_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf15.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("IE 6.0 - Banca Internet_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" >
<Disp><![CDATA[Banca Internet - v3-4-0-prepro]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32" >
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:44:27]]></Time>
<Step rID="T33" >
<Obj plainTxt="False" ><![CDATA[IE 6.0 - Banca Internet_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:27]]></Time>
<Step rID="T34" >
<Obj plainTxt="False" ><![CDATA[activar-12019.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[19/1/07 - 9:44:27]]></Time>
<NodeArgs eType="Replay" icon="16" nRep="58" >
<Disp><![CDATA[activar-12019.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("IE 6.0 - Banca Internet 2").WebCheckBox("activar-12019")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T35" >
<Obj plainTxt="False" ><![CDATA[Activar_Operacion]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Activar_Operacion" started.]]></Details>
<Time><![CDATA[19/1/07 - 9:44:29]]></Time>
<NodeArgs eType="Transaction" icon="12" nRep="59" nType="Start Transaction" >
<Disp><![CDATA[Activar_Operacion]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36" >
<Obj plainTxt="False" ><![CDATA[Aceptar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:29]]></Time>
<NodeArgs eType="Replay" icon="13" nRep="61" >
<Disp><![CDATA[Aceptar.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf19.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("IE 6.0 - Banca Internet 2").WebButton("Aceptar")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="57" >
<Disp><![CDATA[IE 6.0 - Banca Internet_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("IE 6.0 - Banca Internet_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="56" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-4-0-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:44:36]]></Time>
<Step rID="T38" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-3-6-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:36]]></Time>
<Step rID="T39" >
<Obj plainTxt="False" ><![CDATA[head_borde.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["innertext", "  Resultado de la operación", "  Resultado de la operación", 10000]]></Details>
<Time><![CDATA[19/1/07 - 9:44:36]]></Time>
<NodeArgs eType="Replay" icon="14" nRep="66" >
<Disp><![CDATA[head_borde.WaitProperty]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf21.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-3-6-prepro").WebElement("head borde")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T40" >
<Obj plainTxt="False" ><![CDATA[Activar_Operacion]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Activar_Operacion" ended with "Pass" status (Total Duration: 6.8576 sec Wasted Time: 0.2836 sec).]]></Details>
<Time><![CDATA[19/1/07 - 9:44:36]]></Time>
<NodeArgs eType="Transaction" icon="15" nRep="67" nType="End Transaction" >
<Disp><![CDATA[Activar_Operacion]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41" >
<Obj plainTxt="False" ><![CDATA[Volver]]></Obj>
<Details plainTxt="False" ><![CDATA[WebButton]]></Details>
<Time><![CDATA[19/1/07 - 9:44:37]]></Time>
<HtmlStep rID="T42">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css">
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Checkpoint "Volver": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 19/1/07 - 9:44:37</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">Volver Results&nbsp;</td></tr>
<tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Property Value&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<TD class="Text" Title="">html tag&nbsp;</TD>
				<TD class="Text" Title="">INPUT&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><TR>
				<TD class="Text" Title="">innertext&nbsp;</TD>
				<TD class="Text" Title="">&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><TR>
				<TD class="Text" Title="">name&nbsp;</TD>
				<TD class="Text" Title="">Volver&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><TR>
				<TD class="Text" Title="">type&nbsp;</TD>
				<TD class="Text" Title="">submit&nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<NodeArgs eType="Verification" icon="17" nRep="69" status="Passed" >
<Disp><![CDATA[Checkpoint "Volver"]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf23.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-3-6-prepro").WebButton("Volver")]]></ASHilite>
</BtmPane>
</NodeArgs>
</HtmlStep>
<Step rID="T43" >
<Obj plainTxt="False" ><![CDATA[Deslogueo]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Deslogueo" started.]]></Details>
<Time><![CDATA[19/1/07 - 9:44:37]]></Time>
<NodeArgs eType="Transaction" icon="12" nRep="70" nType="Start Transaction" >
<Disp><![CDATA[Deslogueo]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="13" nRep="68" status="Passed" >
<Disp><![CDATA[Volver]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf22.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-3-6-prepro").WebButton("Volver")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="65" status="Passed" >
<Disp><![CDATA[Banca Internet - v3-3-6-prepro]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf20.xml]]></Path>
<ASHilite><![CDATA[Browser("Banca Internet - v3-4-0-prepro").Page("Banca Internet - v3-3-6-prepro")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="64" status="Passed" >
<Disp><![CDATA[Banca Internet - v3-4-0-prepro]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44" >
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:44:38]]></Time>
<Step rID="T45" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-3-0-prepro_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:38]]></Time>
<Step rID="T46" >
<Obj plainTxt="False" ><![CDATA[Salir.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:38]]></Time>
<NodeArgs eType="Replay" icon="18" nRep="75" >
<Disp><![CDATA[Salir.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf25.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro 2").Image("Salir")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="74" >
<Disp><![CDATA[Banca Internet - v3-3-0-prepro_2]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf24.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro_2")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47" >
<Obj plainTxt="False" ><![CDATA[Banco Credicoop Coop.]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:41]]></Time>
<Step rID="T48" >
<Obj plainTxt="False" ><![CDATA[Banco Credicoop Coop..Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:42]]></Time>
<NodeArgs eType="Replay" icon="9" nRep="79" >
<Disp><![CDATA[Banco Credicoop Coop..Sync]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf27.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banco Credicoop Coop.")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T49" >
<Obj plainTxt="False" ><![CDATA[Deslogueo]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Deslogueo" ended with "Pass" status (Total Duration: 4.2785 sec Wasted Time: 0.0464 sec).]]></Details>
<Time><![CDATA[19/1/07 - 9:44:42]]></Time>
<NodeArgs eType="Transaction" icon="15" nRep="80" nType="End Transaction" >
<Disp><![CDATA[Deslogueo]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="78" >
<Disp><![CDATA[Banco Credicoop Coop.]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf26.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banco Credicoop Coop.")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T50" >
<Obj plainTxt="False" ><![CDATA[Browser.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:43]]></Time>
<NodeArgs eType="Replay" icon="5" nRep="81" >
<Disp><![CDATA[Browser.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="73" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="19/1/07 - 9:42:15" eTime="19/1/07 - 9:44:43" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[Activar la Operacion Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="8" status="Passed" >
<Disp><![CDATA[CT152 - Activar Operacion Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T51" iterID="2" >
<Action rID="T52">
<AName><![CDATA[Activar la Operacion]]></AName>
<Step rID="T53" >
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[19/1/07 - 9:44:46]]></Time>
<Step rID="T54" >
<Obj plainTxt="False" ><![CDATA[Alerta de seguridad]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[19/1/07 - 9:44:46]]></Time>
<Step rID="T55" >
<Obj plainTxt="False" ><![CDATA[Sí.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:46]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="89" >
<Disp><![CDATA[Sí.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="88" >
<Disp><![CDATA[Alerta de seguridad]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T56" >
<Obj plainTxt="False" ><![CDATA[Autenticación del cliente]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[19/1/07 - 9:44:46]]></Time>
<Step rID="T57" >
<Obj plainTxt="False" ><![CDATA[El sitio Web que quiere.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["203300 - REY Y MILBERG SA"]]></Details>
<Time><![CDATA[19/1/07 - 9:44:46]]></Time>
<NodeArgs eType="Replay" icon="8" nRep="92" >
<Disp><![CDATA[El sitio Web que quiere.Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
<Path><![CDATA[ZIP::Act1\Row0\ssf29.xml]]></Path>
<ASHilite><![CDATA[1378130]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T58" >
<Obj plainTxt="False" ><![CDATA[Aceptar.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[19/1/07 - 9:44:48]]></Time>
<NodeArgs eType="Replay" icon="7" nRep="94" >
<Disp><![CDATA[Aceptar.Click]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="91" >
<Disp><![CDATA[Autenticación del cliente]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen">
<Path><![CDATA[ZIP::Act1\Row0\ssf28.xml]]></Path>
<ASHilite><![CDATA[2229992]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T59" >
<Obj plainTxt="False" ><![CDATA[Banca Internet - v3-3-0-prepro]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[19/1/07 - 9:44:50]]></Time>
<Step rID="T60" >
<Obj plainTxt="False" ><![CDATA[docType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["DNI PARA EXTRANJEROS"]]></Details>
<Time><![CDATA[19/1/07 - 9:44:50]]></Time>
<NodeArgs eType="Replay" icon="10" nRep="99" >
<Disp><![CDATA[docType.Select]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf31.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro").WebList("docType")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T61" >
<Obj plainTxt="False" ><![CDATA[nroDoc.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["93975837"]]></Details>
<Time><![CDATA[19/1/07 - 9:44:51]]></Time>
<NodeArgs eType="Replay" icon="11" nRep="101" >
<Disp><![CDATA[nroDoc.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb">
<Path><![CDATA[ZIP::Act1\Row0\ssf32.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro").WebEdit("nroDoc")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="98" >
<Disp><![CDATA[Banca Internet - v3-3-0-prepro]]></Disp>
<BtmPane vType="HTMLSNSH">
<Path><![CDATA[ZIP::Act1\Row0\ssf30.xml]]></Path>
<ASHilite><![CDATA[Browser("Browser").Page("Banca Internet - v3-3-0-prepro")]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>